using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.Text;

namespace NotifyGen.Generator;

public sealed partial class NotifyGenerator
{
    /// <summary>
    /// Generates the source code for a class.
    /// </summary>
    private static void GenerateSource(
        SourceProductionContext context,
        NotificationTypeInfo classInfo
    )
    {
        if (!classInfo.CanGenerate)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (classInfo.IsSuppressable)
            sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(classInfo.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {classInfo.Namespace}");
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : "";
        for (var index = 0; index < classInfo.TypeDeclarations.Length; index++)
        {
            var declaration = classInfo.TypeDeclarations[index];
            var isTarget = index == classInfo.TypeDeclarations.Length - 1;
            var requiredModifiers =
                declaration.RequiredModifiers.Length == 0
                    ? string.Empty
                    : string.Join(" ", declaration.RequiredModifiers) + " ";
            if (
                isTarget
                && classInfo.Fields.Any(static field => field.RequiresUnsafe)
                && !declaration.RequiredModifiers.Contains("unsafe")
            )
            {
                requiredModifiers += "unsafe ";
            }

            var interfaces = string.Empty;
            if (isTarget)
            {
                var interfaceList = new List<string>();
                if (!classInfo.AlreadyImplementsInpc)
                    interfaceList.Add("INotifyPropertyChanged");
                if (classInfo.ImplementChanging && !classInfo.AlreadyImplementsInpcChanging)
                    interfaceList.Add("INotifyPropertyChanging");
                interfaces =
                    interfaceList.Count == 0
                        ? string.Empty
                        : " : " + string.Join(", ", interfaceList);
            }

            sb.AppendLine(
                $"{indent}{declaration.Accessibility} {requiredModifiers}partial {declaration.Keyword} {declaration.Name}{declaration.TypeParameterList}{interfaces}"
            );
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // PropertyChanged event (only if not already implemented)
        if (!classInfo.AlreadyImplementsInpc)
        {
            sb.AppendLine(
                $"{indent}    public event PropertyChangedEventHandler? PropertyChanged;"
            );
            sb.AppendLine();
        }

        // PropertyChanging event (only if ImplementChanging is true and not already implemented)
        if (classInfo.ImplementChanging && !classInfo.AlreadyImplementsInpcChanging)
        {
            sb.AppendLine(
                $"{indent}    public event PropertyChangingEventHandler? PropertyChanging;"
            );
            sb.AppendLine();
        }

        // Suppression fields (only if IsSuppressable)
        if (classInfo.IsSuppressable)
        {
            // Generate static HashSet for AlwaysNotify properties
            if (classInfo.AlwaysNotifyProperties.Length > 0)
            {
                sb.AppendLine(
                    $"{indent}    private static readonly HashSet<string> _neverSuppressedProperties = new()"
                );
                sb.AppendLine($"{indent}    {{");
                foreach (var prop in classInfo.AlwaysNotifyProperties)
                {
                    sb.AppendLine($"{indent}        \"{prop}\",");
                }
                sb.AppendLine($"{indent}    }};");
                sb.AppendLine();
            }

            sb.AppendLine($"{indent}    private int _notificationSuppressionCount;");
            sb.AppendLine($"{indent}    private HashSet<string>? _pendingNotifications;");
            sb.AppendLine();
        }

        if (classInfo.IsSuppressable && classInfo.AlreadyImplementsInpc)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    private void __notifyGenRaisePropertyChanged(string propertyName)");
            sb.AppendLine($"{indent}    {{");
            if (classInfo.AlwaysNotifyProperties.Length > 0)
            {
                sb.AppendLine(
                    $"{indent}        if (_notificationSuppressionCount > 0 && !_neverSuppressedProperties.Contains(propertyName))"
                );
            }
            else
            {
                sb.AppendLine($"{indent}        if (_notificationSuppressionCount > 0)");
            }
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            _pendingNotifications ??= new HashSet<string>();");
            sb.AppendLine($"{indent}            _pendingNotifications.Add(propertyName);");
            sb.AppendLine($"{indent}            return;");
            sb.AppendLine($"{indent}        }}");
            AppendPropertyChangedVariableCall(
                sb,
                indent + "        ",
                classInfo.PropertyChangedInvoker
            );
            sb.AppendLine($"{indent}    }}");
        }

        // Generate child-property subscription state and handlers.
        foreach (var field in classInfo.Fields)
        {
            if (HasSubPropertySubscription(field))
            {
                GenerateSubPropertyMembers(
                    sb,
                    field,
                    indent,
                    classInfo.PropertyChangedInvoker,
                    classInfo.IsSuppressable && classInfo.AlreadyImplementsInpc
                );
                sb.AppendLine();
            }

            if (HasCollectionSubscription(field))
            {
                GenerateCollectionMembers(
                    sb,
                    field,
                    indent,
                    classInfo.PropertyChangedInvoker,
                    classInfo.IsSuppressable && classInfo.AlreadyImplementsInpc
                );
                sb.AppendLine();
            }
        }

        // Generate properties
        foreach (var field in classInfo.Fields)
        {
            GenerateProperty(
                sb,
                field,
                indent,
                classInfo.ImplementChanging,
                classInfo.MemberNames,
                classInfo.PropertyChangedInvoker,
                classInfo.PropertyChangingInvoker,
                classInfo.IsSuppressable && classInfo.AlreadyImplementsInpc
            );
            sb.AppendLine();
        }

        // OnPropertyChanged method (only if not already implemented)
        if (!classInfo.AlreadyImplementsInpc)
        {
            sb.AppendLine(
                $"{indent}    protected virtual void OnPropertyChanged([CallerMemberName] string? propertyName = null)"
            );
            sb.AppendLine($"{indent}    {{");
            if (classInfo.IsSuppressable)
            {
                if (classInfo.AlwaysNotifyProperties.Length > 0)
                {
                    // Check if property should never be suppressed
                    sb.AppendLine(
                        $"{indent}        if (_notificationSuppressionCount > 0 && !_neverSuppressedProperties.Contains(propertyName ?? \"\"))"
                    );
                }
                else
                {
                    sb.AppendLine($"{indent}        if (_notificationSuppressionCount > 0)");
                }
                sb.AppendLine($"{indent}        {{");
                sb.AppendLine(
                    $"{indent}            _pendingNotifications ??= new HashSet<string>();"
                );
                sb.AppendLine($"{indent}            _pendingNotifications.Add(propertyName!);");
                sb.AppendLine($"{indent}            return;");
                sb.AppendLine($"{indent}        }}");
            }
            sb.AppendLine(
                $"{indent}        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));"
            );
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        // OnPropertyChanging method (only if ImplementChanging is true and not already implemented)
        if (classInfo.ImplementChanging && !classInfo.AlreadyImplementsInpcChanging)
        {
            sb.AppendLine(
                $"{indent}    protected virtual void OnPropertyChanging([CallerMemberName] string? propertyName = null)"
            );
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine(
                $"{indent}        PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propertyName));"
            );
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
        }

        // Generate partial hooks
        foreach (var field in classInfo.Fields)
        {
            sb.AppendLine(
                $"{indent}    partial void On{field.PropertyName}Changing({field.TypeName} oldValue, {field.TypeName} newValue);"
            );
            sb.AppendLine($"{indent}    partial void On{field.PropertyName}Changed();");
            if (!field.HasNonPartialTypedChangedHook)
            {
                sb.AppendLine(
                    $"{indent}    partial void On{field.PropertyName}Changed({field.TypeName} oldValue, {field.TypeName} newValue);"
                );
            }
        }

        // Suppression methods (only if IsSuppressable)
        if (classInfo.IsSuppressable)
        {
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine(
                $"{indent}    /// Suppresses PropertyChanged notifications until the returned IDisposable is disposed."
            );
            sb.AppendLine($"{indent}    /// Supports nested suppression scopes.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    public IDisposable SuppressNotifications()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        _notificationSuppressionCount++;");
            sb.AppendLine($"{indent}        return new NotificationSuppressor(this);");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    private void ResumeNotifications()");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine(
                $"{indent}        if (--_notificationSuppressionCount == 0 && _pendingNotifications != null)"
            );
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine(
                $"{indent}            foreach (var propertyName in _pendingNotifications)"
            );
            sb.AppendLine($"{indent}            {{");
            if (classInfo.AlreadyImplementsInpc)
            {
                AppendPropertyChangedVariableCall(
                    sb,
                    indent + "                ",
                    classInfo.PropertyChangedInvoker
                );
            }
            else
            {
                sb.AppendLine(
                    $"{indent}                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));"
                );
            }
            sb.AppendLine($"{indent}            }}");
            sb.AppendLine($"{indent}            _pendingNotifications.Clear();");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine();
            sb.AppendLine($"{indent}    private sealed class NotificationSuppressor : IDisposable");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine(
                $"{indent}        private readonly {classInfo.TargetType.Name}{classInfo.TargetType.TypeParameterList} _owner;"
            );
            sb.AppendLine(
                $"{indent}        public NotificationSuppressor({classInfo.TargetType.Name}{classInfo.TargetType.TypeParameterList} owner) => _owner = owner;"
            );
            sb.AppendLine(
                $"{indent}        public void Dispose() => _owner.ResumeNotifications();"
            );
            sb.AppendLine($"{indent}    }}");
        }

        for (var index = classInfo.TypeDeclarations.Length - 1; index >= 0; index--)
        {
            indent = indent.Substring(0, indent.Length - 4);
            sb.AppendLine($"{indent}}}");
        }

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        var sourceText = SourceText.From(sb.ToString(), Encoding.UTF8);
        context.AddSource(
            SourceHintName.Create(classInfo.TargetType.MetadataIdentity, classInfo.TargetType.Name),
            sourceText
        );
    }

    private static void AppendPropertyChangedCall(
        StringBuilder sb,
        string indent,
        string propertyName,
        PropertyChangedInvokerKind invoker,
        bool useSuppressionWrapper = false
    )
    {
        var argument = QuoteString(propertyName);
        if (useSuppressionWrapper)
        {
            sb.AppendLine($"{indent}__notifyGenRaisePropertyChanged({argument});");
            return;
        }
        if (invoker == PropertyChangedInvokerKind.EventArgs)
        {
            sb.AppendLine(
                $"{indent}OnPropertyChanged(new global::System.ComponentModel.PropertyChangedEventArgs({argument}));"
            );
        }
        else
        {
            sb.AppendLine($"{indent}OnPropertyChanged({argument});");
        }
    }

    private static void AppendPropertyChangedVariableCall(
        StringBuilder sb,
        string indent,
        PropertyChangedInvokerKind invoker
    )
    {
        if (invoker == PropertyChangedInvokerKind.EventArgs)
        {
            sb.AppendLine(
                $"{indent}OnPropertyChanged(new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));"
            );
        }
        else
        {
            sb.AppendLine($"{indent}OnPropertyChanged(propertyName);");
        }
    }

    private static void AppendPropertyChangingCall(
        StringBuilder sb,
        string indent,
        string propertyName,
        PropertyChangingInvokerKind invoker
    )
    {
        var argument = QuoteString(propertyName);
        if (invoker == PropertyChangingInvokerKind.EventArgs)
        {
            sb.AppendLine(
                $"{indent}OnPropertyChanging(new global::System.ComponentModel.PropertyChangingEventArgs({argument}));"
            );
        }
        else
        {
            sb.AppendLine($"{indent}OnPropertyChanging({argument});");
        }
    }

    private static string EnsureNonNull(string expression) =>
        expression.EndsWith("!", StringComparison.Ordinal) ? expression : $"{expression}!";

    private static string GetOldValueLocalName(ImmutableArray<string> memberNames)
    {
        const string baseName = "__notifyGenOldValue";
        var candidate = baseName;
        var suffix = 0;
        while (memberNames.Contains(candidate, StringComparer.Ordinal))
        {
            suffix++;
            candidate = $"{baseName}{suffix}";
        }

        return candidate;
    }

    /// <summary>
    /// Generates a single property.
    /// </summary>
    private static void GenerateProperty(
        StringBuilder sb,
        FieldInfo field,
        string indent,
        bool implementChanging,
        ImmutableArray<string> memberNames,
        PropertyChangedInvokerKind invoker,
        PropertyChangingInvokerKind changingInvoker,
        bool useSuppressionWrapper
    )
    {
        if (!field.PropertyAttributes.IsDefaultOrEmpty)
        {
            foreach (var attribute in field.PropertyAttributes)
            {
                sb.AppendLine($"{indent}    {attribute}");
            }
        }

        if (field.IsPartialProperty && field.NeedsNullableBackingField)
        {
            sb.AppendLine(
                $"{indent}    [field: global::System.Diagnostics.CodeAnalysis.MaybeNull, global::System.Diagnostics.CodeAnalysis.AllowNull]"
            );
        }

        var partialModifier = field.IsPartialProperty ? " partial" : string.Empty;
        var backingValue = field.NeedsNullableBackingField
            ? $"{field.FieldName}!"
            : field.FieldName;
        var hasSubPropertySubscription = HasSubPropertySubscription(field);
        var subPropertyPrefix = hasSubPropertySubscription
            ? GetSubPropertyMemberPrefix(field)
            : string.Empty;
        var hasCollectionSubscription = HasCollectionSubscription(field);
        var collectionPrefix = hasCollectionSubscription
            ? GetCollectionMemberPrefix(field)
            : string.Empty;
        sb.AppendLine(
            $"{indent}    {field.PropertyAccessibility}{partialModifier} {field.TypeName} {field.PropertyName}"
        );
        sb.AppendLine($"{indent}    {{");
        var getterModifier = field.GetterAccess != null ? $"{field.GetterAccess} " : "";
        if (
            hasSubPropertySubscription
            || hasCollectionSubscription
            || !field.GetterAttributes.IsDefaultOrEmpty
        )
        {
            if (!field.GetterAttributes.IsDefaultOrEmpty)
            {
                foreach (var attribute in field.GetterAttributes)
                    sb.AppendLine($"{indent}        {attribute}");
            }

            sb.AppendLine($"{indent}        {getterModifier}get");
            sb.AppendLine($"{indent}        {{");
            if (hasSubPropertySubscription)
                sb.AppendLine($"{indent}            {subPropertyPrefix}Ensure({backingValue});");
            if (hasCollectionSubscription)
                sb.AppendLine($"{indent}            {collectionPrefix}Ensure({backingValue});");
            sb.AppendLine($"{indent}            return {backingValue};");
            sb.AppendLine($"{indent}        }}");
        }
        else
        {
            sb.AppendLine($"{indent}        {getterModifier}get => {backingValue};");
        }
        var setterModifier = field.SetterAccess != null ? $"{field.SetterAccess} " : "";
        if (!field.SetterAttributes.IsDefaultOrEmpty)
        {
            foreach (var attribute in field.SetterAttributes)
                sb.AppendLine($"{indent}        {attribute}");
        }
        sb.AppendLine($"{indent}        {setterModifier}set");
        sb.AppendLine($"{indent}        {{");
        if (hasSubPropertySubscription)
        {
            sb.AppendLine($"{indent}            {subPropertyPrefix}Ensure({backingValue});");
        }
        if (hasCollectionSubscription)
        {
            sb.AppendLine($"{indent}            {collectionPrefix}Ensure({backingValue});");
        }
        // Pointer-like types use native-int equality to avoid function-pointer comparison warnings.
        if (field.IsPrimitiveType && field.RequiresUnsafe)
        {
            sb.AppendLine(
                $"{indent}            if ((nint){field.FieldName} == (nint)value) return;"
            );
        }
        else if (field.IsPrimitiveType)
        {
            sb.AppendLine($"{indent}            if ({backingValue} == value) return;");
        }
        else
        {
            sb.AppendLine(
                $"{indent}            if (EqualityComparer<{field.TypeName}>.Default.Equals({backingValue}, value)) return;"
            );
        }
        var oldValueLocalName = GetOldValueLocalName(memberNames);
        var isDynamicType = field.TypeName == "dynamic" || field.TypeName == "dynamic?";
        var oldValueArgument = isDynamicType
            ? $"((global::System.Object?){oldValueLocalName})!"
            : oldValueLocalName;
        var newValueArgument = isDynamicType
            ? "((global::System.Object?)value)!"
            : "value";
        var changingOldValueArgument = isDynamicType ? oldValueArgument : backingValue;
        var changingNewValueArgument = isDynamicType ? newValueArgument : "value";
        var existingOldHookType = field.ExistingTypedChangedHookParameterTypeName;
        var existingNewHookType = field.ExistingTypedChangedHookNewParameterTypeName;
        var typedOldValueArgument = existingOldHookType is not null
            ? $"({existingOldHookType})({EnsureNonNull(oldValueArgument)})"
            : field.IsNullable && !isDynamicType
                ? $"{oldValueArgument}!"
                : oldValueArgument;
        var typedNewValueArgument = existingNewHookType is not null
            ? $"({existingNewHookType})({EnsureNonNull(newValueArgument)})"
            : field.IsNullable && !isDynamicType
                ? $"{newValueArgument}!"
                : newValueArgument;
        sb.AppendLine($"{indent}            var {oldValueLocalName} = {backingValue};");
        // Fire PropertyChanging event if enabled
        if (implementChanging)
        {
            if (changingInvoker == PropertyChangingInvokerKind.Generated)
                sb.AppendLine($"{indent}            OnPropertyChanging();");
            else
                AppendPropertyChangingCall(
                    sb,
                    indent + "            ",
                    field.PropertyName,
                    changingInvoker
                );
        }
        sb.AppendLine(
            $"{indent}            On{field.PropertyName}Changing({changingOldValueArgument}, {changingNewValueArgument});"
        );
        sb.AppendLine($"{indent}            {field.FieldName} = value;");
        if (hasSubPropertySubscription)
        {
            sb.AppendLine($"{indent}            {subPropertyPrefix}Update(value);");
        }
        if (hasCollectionSubscription)
        {
            sb.AppendLine($"{indent}            {collectionPrefix}Update(value);");
        }
        if (invoker == PropertyChangedInvokerKind.Generated)
            sb.AppendLine($"{indent}            OnPropertyChanged();");
        else
            AppendPropertyChangedCall(
                sb,
                indent + "            ",
                field.PropertyName,
                invoker,
                useSuppressionWrapper: useSuppressionWrapper
            );

        // NotifyAlso properties
        foreach (var alsoNotify in field.AlsoNotify)
        {
            AppendPropertyChangedCall(
                sb,
                indent + "            ",
                alsoNotify,
                invoker,
                useSuppressionWrapper: useSuppressionWrapper
            );
        }

        // NotifyCanExecuteChanged for commands (requires IRelayCommand or compatible type)
        foreach (var command in field.CommandsToNotify)
        {
            sb.AppendLine($"{indent}            {command}?.NotifyCanExecuteChanged();");
        }

        sb.AppendLine($"{indent}            On{field.PropertyName}Changed();");
        sb.AppendLine(
            $"{indent}            On{field.PropertyName}Changed({typedOldValueArgument}, {typedNewValueArgument});"
        );
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
    }

}
